# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
    - name: Set up JDK 23
      uses: actions/setup-java@v4.5.0
      with:
        java-version: '23'
        distribution: 'oracle'

    - name: Install GitVersion for Gradle
      run: |
          wget -q -O gitversion.tar.gz https://github.com/GitTools/GitVersion/releases/download/6.0.5/gitversion-linux-x64-6.0.5.tar.gz
          mkdir gitversion_extracted
          tar -xzf gitversion.tar.gz -C gitversion_extracted
          ls -R gitversion_extracted
          sudo mv gitversion_extracted/gitversion /usr/local/bin/gitversion
          sudo chmod +x /usr/local/bin/gitversion
          
    - name: Setup Gradle 8.11.1
      uses: gradle/actions/setup-gradle@v4
      with:
       gradle-version: '8.11.1'
    #
    - name: Build with Gradle 8.11.1
      run: gradle build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 23
      uses: actions/setup-java@v4.5.0
      with:
        java-version: '23'
        distribution: 'oracle'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
       gradle-version: '8.11.1'

    - name: Setup Gradle Wrapper
      run: gradle wrapper

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
